#!/bin/bash

build() {
    cp /etc/encswap.conf "$BUILDROOT/encswap.conf"
    add_runscript
}

help() {
    cat <<HELPEOF
This hook initializes support for resuming from an encrypted swapfile for which
the keyfile is located in the encrypted filesystem. The swap device and the
location of the keyfile is configured in /etc/encswap.conf

To use this module, edit /etc/mkinitcpio.conf and add "encswap" to HOOKS,
after "encrypt".

encswap is designed to support resumption after hibernation, so the "suspend"
hook is unnecessary and should not be used. Do not set any suspend-related
kernel parameters.
The encswap.service systemd service is responsible for refreshing a key
and enabling swap before hibernation.

After editing the configuration, rebuild the initramfs image:
mkinitcpio -p linux

HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
